### PR TITLE
v0.4.3

### PR DESCRIPTION
**Pull request by yegortimofeyenko**
v0.4.3
∙ refactored code in general for readability/scalability
∙ created HAction class based on previous new_action function
    - HAactions are populated in the MainWindow and actions.py is no longer needed/was removed
∙ added:
    - preview mode
        - preview is filtered by default based on include files/exclude files etc.
        - thumbnails can be cached or generated in memory
        - alder32 checksum is computed on files before pulling cached thumbnails
            - if file changed thumbnail will be recalculated
        - during testing sometimes MemoryError would show up when memory is not full and sometimes MemoryError would show up when memory is actually full
        - use small cached thumbnails if CPU memory is low and image count is high

        thumbnails_in_memory=True
        - thumbnails will be generated in memory each time preview mode is started
        - images with transparent backgrounds will show the background in their thumbnails
        - slower thumbnail generation for large number of file

        thumbnails_in_memory=False:
        - thumbnails will be saved to the drive
        - thumbnails will not be re-generated unless thumbnail size is increased
        - images with transparent backgrounds will show white  background in their thumbnails
        - faster thumbnail generation for large number of file after initial thumbnail generation is complete
        - thumbnails are automatically re-generated if the image files change/are edited (i.e. adler32 sum is different)
∙ added
    - fast zoom option
        fast_zoom=True: same as in v0.4.2
        - faster
        - photos look good
        - images with text/lines/vector graphics show artifacts upon zoom
        - cursor position coordinates reflect actual image dimensions regardless of zoom state
        - pressing CTRL+R will temporarily disable fast zoom

        fast_zoom=False:
        - slower
        - both photos and images with text/lines/vector graphics look perfect
        - cursor position coordinates reflect resized image dimensions unless Zoom is 1.0
∙ added
    - settings dialog
∙ fixed:
    - was: info panel could not be reopened by user if close
    - now:
        - info panel is not closeable by user
        - is deleted programmaticaly opon programmatic close
        - added show/hide info panel button
∙ fixed:
    - was: canvas.mouse_color_label was moving left/right, not staying fixed
    - now: stays fixed
∙ hvdb.get_folder ← removed folder keyword ← it wasn't used
∙ added:
    - mainWindow.open_file_dialog now filters images based on utils.FORMATS
∙ fixed:
    - was: opening a file would display the first file in the folder
    - now: opening a file displays the opened file
        - if you add a comparison folder, switching to comparison view will show that file
∙ fixed:
    - now: last open directory is automatically loaded into file open dialog
∙ fixed:
    - now: canvas.comparison_label is cleared from mainWindow.dockWidget when clearing comparison when in main view
∙ fixed:
    - was: IndexError was causing crash when all images were filtered based on given filter
    - now: Message box is displayed, and the filter state remains unchanged
∙ canvas:
    - refactored canvas.show_image
        - moved QT operations into HVScene.set_image(self, qImage, width, height)
∙ HVScene:
    - refactored
    - changed: no need to feed PIL.image width and height into HVScene because QPixel and QImage .width() and .height() return the same dimensions
        see disabled HVScene.set_image(self, qImage, width, height)
        → HVScene.set_image(self, img_path) contains relevant QT code in the widget that uses it
∙ disabled draw and edit in the menu bar ← they are blank

### CODE REVIEW

**Comment by xinntao** [comment]
@yegortimofeyenko 
Thanks for contributing! 😄  

There are a lot of changes. I will also learn your codes and review them later! 
Currently, it seems that the code style cannot pass the PyLint. If possible, could you help to fix it first? 
(Actually, the current code style may not be good, such as the line number limit is too short, I will extend it to 120 after merging this pull request. But for this pull request, we may better to keep the old style first~)

Thank you again :-)

**Comment by xinntao** [comment]
@yegortimofeyenko 
Thanks for contributing! 😄  

There are a lot of changes. I will also learn and review it later! 
Currently, it seems that the code style cannot pass the PyLint. If possible, could you help to fix it first?

(Actually, the current code style may not be good enough, for example, the line number limit is too short. I will change it to 120 after merging this pull request. But for this pull request, we may better to keep the current code style.)

Thank you again:-)

**Comment by xinntao** [comment]
@yegortimofeyenko 
Thanks for contributing! 😄  

There are a lot of changes. I will also learn and review it later! 
Currently, it seems that the code style cannot pass the PyLint. If possible, could you help to fix it first?

(Actually, the current code style may not be good enough, for example, the line number limit is too short. I will change it to 120 after merging this pull request. But for this pull request, we may better to keep the current code style.)

Thank you again:-)

**Comment by yegortimofeyenko** [comment]
I'll be happy to! Could you, please, email me your PyLint pylintrc config file?

**Comment by xinntao** [comment]
@yegortimofeyenko 

Sorry for the late reply. 

1. I use flake8 and yapf instead of pylint.  I put the format file in [`.vscode/setting.json`](https://github.com/xinntao/HandyView/blob/master/.vscode/settings.json). If you do not use vscode, you may need to configure it accordingly. 
2. Really sorry that I found I have un-pushed local changes. So it may have conflicts with your pull request. You may need to solve those conflicts first. Sorry for the inconvenience.

If you have any problems, Please let me know 😄

**Comment by xinntao** [comment]
@yegortimofeyenko  If you need help, please let me know, I can help to merge the conflicts :-)

**Comment by yegortimofeyenko** [comment]
No problem!

Unfortunately, I am out of time allocated to HandyView beyond style adjustments. My primary goal was to establish a method for accurate rendering of scaled PDF-like images in QT using QGraphicsView before starting the next project.

I added the preview feature and created the pull request as a courtesy because you asked. I'll leave the forked and edited version up. You are welcome to incorporate/modify any code if you find it useful. 

I enjoyed looking over your work, and learning from your programming habits :)

**Comment by xinntao** [comment]
Thanks @yegortimofeyenko 

I will finish the left work 😄  
Thanks for your contribution

**Pull request closed without merging**
